package dev.sushrut.loglens;

/**
 * Build-time constants. Generated by the templating-maven-plugin from
 * {@code src/main/java-templates/.../BuildInfo.java} with the Maven project
 * version substituted in, so the CLI version tracks the release instead of a
 * hand-maintained string. Baked in at compile time — no runtime resource or
 * manifest lookup — which keeps it working under GraalVM native-image.
 */
final class BuildInfo {
    static final String VERSION = "${project.version}";

    private BuildInfo() {}
}
